function [fitresult, gof] = fct_createFit1(xdata, ydata, zdata)
%CREATEFIT(NEWXPPRE,NEWYPPRE,NEWZPPRE)
%  Get linear polynomial model of surface through input data.
%  Input:
%       xdata - Input data of x-axis
%       ydata - Input data of y-axis
%       zdata - Input data of z-axis
%
%  Output:
%      fitresult   - equation of surface model
%      gof         - structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 20-May-2019 16:18:03

% Contributed authors: Ravi Deepak (depakroshanblu@gmail.com), Marc Bartholet, Caroline Heimhofer
% Affiliation: Laboratory of Movement Biomechanics, ETH Zurich, Switzerland
% Last Modified: June 2019


%% 'Fit Surface'
[xData, yData, zData] = prepareSurfaceData(xdata, ydata, zdata );

% Set up fittype and options.
ft = fittype( 'poly11' );

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft);
